# Generated by Django 3.0.8 on 2020-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('plot', models.CharField(max_length=1000)),
                ('actors', models.ManyToManyField(to='filmapp.Actors')),
                ('directors', models.ManyToManyField(to='filmapp.Directors')),
            ],
        ),
    ]
