# Generated by Django 3.0.8 on 2020-07-30 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 30, 13, 58, 7, 862089)),
        ),
    ]
