# Generated by Django 3.0.8 on 2020-07-31 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_auto_20200731_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='directors',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 8, 56, 35, 802287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='directors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 8, 56, 35, 802287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 8, 56, 35, 851839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
