# Generated by Django 3.0.8 on 2020-07-31 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 8, 37, 26, 478304)),
        ),
    ]
