# Generated by Django 3.1 on 2020-08-05 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 10, 11, 36, 622809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='directors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 10, 11, 36, 622809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 10, 11, 36, 624859, tzinfo=utc)),
        ),
    ]
