# Generated by Django 3.0.8 on 2020-07-31 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_auto_20200731_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 8, 41, 49, 363859, tzinfo=utc)),
        ),
    ]
