# Generated by Django 3.1 on 2020-08-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_auto_20200819_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, to='moviesapp.Actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(blank=True, to='moviesapp.Directors'),
        ),
    ]
