# Generated by Django 3.0.8 on 2020-07-31 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0006_auto_20200731_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 13, 14, 59, 712618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='directors',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 13, 14, 59, 712618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 13, 14, 59, 764574, tzinfo=utc)),
        ),
    ]
